apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkhfp6896-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkhfp6896-tenant-component
    app.kubernetes.io/part-of: loadkhfp6896-tenant-app
  name: loadkhfp6896-tenant-component
  namespace: loadkhfp6896-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadkhfp6896-tenant-component
status:
  loadBalancer: {}
